### ISSUE TITLE
Last_issue_to_check_test_env

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#10]
Last_issue_to_check_test_env

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x833f93d16bbdbc1402c6b2eed94087af74f5ff9ce952042dd7cd9a6993118a8c](https://ropsten.etherscan.io/tx/0x833f93d16bbdbc1402c6b2eed94087af74f5ff9ce952042dd7cd9a6993118a8c)
