### ISSUE TITLE
A lot of claims

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#104]
A lot of claims
A lot of claims

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x7d2a1e53f4a5b9221742ade11f0d71bf12d91e6f23f086d4dda69ea2f5a8bee6](https://ropsten.etherscan.io/tx/0x7d2a1e53f4a5b9221742ade11f0d71bf12d91e6f23f086d4dda69ea2f5a8bee6)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd3fe33b404bb0f89829c875fe0236e96409e92f3285a3d5c40e01f04f0d63b63](https://ropsten.etherscan.io/tx/0xd3fe33b404bb0f89829c875fe0236e96409e92f3285a3d5c40e01f04f0d63b63)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x2278d574af72e721034a40dcfd669e2e4426c72feee565b0949089bae753910a](https://ropsten.etherscan.io/tx/0x2278d574af72e721034a40dcfd669e2e4426c72feee565b0949089bae753910a)
