### ISSUE TITLE
Claim is already on another bounty

### ISSUE THREAD

**Issue by churik** [TestingEnvENV/TestEnvAtt5#105]
Claim is already on another bounty

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x5853b94768bc287689eb4fd65d491b02aa81b5a92706525049c172bc690f2439](https://ropsten.etherscan.io/tx/0x5853b94768bc287689eb4fd65d491b02aa81b5a92706525049c172bc690f2439)
