### ISSUE TITLE
LongNameLongNameLongNameLongNameLongNameLongNameLongNameLongNameLongNameLongNameLongName

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#11]
LongName

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x60b2d90f6838b10cbbbcd9a1b0bb3ccd047f250e0b0124954352640fe7f9a8bd](https://ropsten.etherscan.io/tx/0x60b2d90f6838b10cbbbcd9a1b0bb3ccd047f250e0b0124954352640fe7f9a8bd)
