### ISSUE TITLE
выаваываваываывыа

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#16]
выаваываваываывыа

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xadce765ae87fcf6a3b21ee42a98c2c7fa50bf35c87bb3acfb76cac624aa6741c](https://ropsten.etherscan.io/tx/0xadce765ae87fcf6a3b21ee42a98c2c7fa50bf35c87bb3acfb76cac624aa6741c)
