### ISSUE TITLE
2 attempt -> several PRs

### ISSUE THREAD

**Issue by churik** [TestingEnvENV/TestEnvAtt5#186]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa03bc660e83bac76617eb7522c8a4414af147a0a3a56f162474213375adf9520](https://ropsten.etherscan.io/tx/0xa03bc660e83bac76617eb7522c8a4414af147a0a3a56f162474213375adf9520)
