### ISSUE TITLE
wer

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#189]
qwer

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xbbae9bce15d34efe04b8f1ddc68c73cb79a8c1735610e0f3fcf57ea60b29a088](https://ropsten.etherscan.io/tx/0xbbae9bce15d34efe04b8f1ddc68c73cb79a8c1735610e0f3fcf57ea60b29a088)
