### ISSUE TITLE
many PRs

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#20]
many PRs

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xac091679a3e146958632aed7f47cb10929c15879364062467f44ba4c5f9d9356](https://ropsten.etherscan.io/tx/0xac091679a3e146958632aed7f47cb10929c15879364062467f44ba4c5f9d9356)
