### ISSUE TITLE
some new issue

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#25]
sdfsdfsdfdfs

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc2abca00bbb054d5e7232a90d2cdfbb3b01c9bb269fffde112e131f2d3f84952](https://ropsten.etherscan.io/tx/0xc2abca00bbb054d5e7232a90d2cdfbb3b01c9bb269fffde112e131f2d3f84952)
