### ISSUE TITLE
Issue with ANT

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#27]
Issue with ANT

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x081a377dd726294bb8f1cbb02cbe8fd56a288f8d0e99dbd59a15fbbda92655ed](https://ropsten.etherscan.io/tx/0x081a377dd726294bb8f1cbb02cbe8fd56a288f8d0e99dbd59a15fbbda92655ed)
