### ISSUE TITLE
Just_to_test_deploy_works

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#28]
Just_to_test_deploy_works

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x7e64762ed28d4d5258f420f072cb67a988e4246c47143085de989e6823681688](https://ropsten.etherscan.io/tx/0x7e64762ed28d4d5258f420f072cb67a988e4246c47143085de989e6823681688)
