### ISSUE TITLE
Test_to_deploy_bounties

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#29]
Test_to_deploy_bounties

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x4e570614f355db362e053c3eddc246f7e91b72a490c51922f5ff93db75bf72a9](https://ropsten.etherscan.io/tx/0x4e570614f355db362e053c3eddc246f7e91b72a490c51922f5ff93db75bf72a9)
