### ISSUE TITLE
Reduce_confirmation

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#34]
Reduce_confirmation

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x76aeb8f0233e37f08a4c3f5ea125e3f33a43dd060d8e6a14657dc9f3942ccbb7](https://ropsten.etherscan.io/tx/0x76aeb8f0233e37f08a4c3f5ea125e3f33a43dd060d8e6a14657dc9f3942ccbb7)
