### ISSUE TITLE
Delete stale extern file_1

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#50]
Delete stale extern file

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa07d516e99f5efac8a9a88ad1c7fbf36f53cb29a2fe0ae7c2addaefa8f1516a2](https://ropsten.etherscan.io/tx/0xa07d516e99f5efac8a9a88ad1c7fbf36f53cb29a2fe0ae7c2addaefa8f1516a2)
