### ISSUE TITLE
NEW_function

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#58]
NEW_Function

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xaafa2f15e849689c5be12b4131997e13454df19e16679c6405e1d01661c8e6b4](https://ropsten.etherscan.io/tx/0xaafa2f15e849689c5be12b4131997e13454df19e16679c6405e1d01661c8e6b4)
