### ISSUE TITLE
On_more

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#62]
On_more

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8febdfba87ef3f1f0f72269e208687db10f1e308f172976f7a7955a9c3b33e15](https://ropsten.etherscan.io/tx/0x8febdfba87ef3f1f0f72269e208687db10f1e308f172976f7a7955a9c3b33e15)
