### ISSUE TITLE
issue_to_check_claims

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#67]
issue_to_check_claims

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x069d9e2a9a54faa84874594c25c5235eff0b5d6c6be83815b2b716c30e2babf7](https://ropsten.etherscan.io/tx/0x069d9e2a9a54faa84874594c25c5235eff0b5d6c6be83815b2b716c30e2babf7)
