### ISSUE TITLE
To check offline trans

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#7]
To check offline trans

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x29b4ce4ccc2a714b22273b16e9f9c8d6914a75d0934e966fc19b5e3650e1e854](https://ropsten.etherscan.io/tx/0x29b4ce4ccc2a714b22273b16e9f9c8d6914a75d0934e966fc19b5e3650e1e854)
