### ISSUE TITLE
issue_to_check_claims_list

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#70]
issue_to_check_claims_list

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xf219fb1f7a8fd18edea0d2654c1191b9bbdaab727f94d99481219df0a0f3e555](https://ropsten.etherscan.io/tx/0xf219fb1f7a8fd18edea0d2654c1191b9bbdaab727f94d99481219df0a0f3e555)
