### ISSUE TITLE
Check+PRs

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#73]
Check+PRs

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x47dfc1b408682875c068847edbd0313f506cf35470fe68a5b77ab82abc481504](https://ropsten.etherscan.io/tx/0x47dfc1b408682875c068847edbd0313f506cf35470fe68a5b77ab82abc481504)
