### ISSUE TITLE
fff

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#74]
ffff

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x1d38ff48a259dbee5cced83bdecaac3bd4ab4f136efd6ec203be298181aa6846](https://ropsten.etherscan.io/tx/0x1d38ff48a259dbee5cced83bdecaac3bd4ab4f136efd6ec203be298181aa6846)
