### ISSUE TITLE
test_deploy

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#77]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x3b22c715f02c4edd2fa0659deabcf17adc53df348d3cbd13ae5b20dc82f7563f](https://ropsten.etherscan.io/tx/0x3b22c715f02c4edd2fa0659deabcf17adc53df348d3cbd13ae5b20dc82f7563f)
