### ISSUE TITLE
test_PRS_list

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#79]
test_PRS_list

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x99605e79c44350c5bc0beafd44b5b02b5978303c0ca5c7a0890e7462789e7340](https://ropsten.etherscan.io/tx/0x99605e79c44350c5bc0beafd44b5b02b5978303c0ca5c7a0890e7462789e7340)
