### ISSUE TITLE
first_issue_bounty

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#80]
firfirst_issue_bounty

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x374b18ddc4e149e6487ef7ca3a657aae6c7c2a21143fc6e0891306a4b895e9bb](https://ropsten.etherscan.io/tx/0x374b18ddc4e149e6487ef7ca3a657aae6c7c2a21143fc6e0891306a4b895e9bb)
