### ISSUE TITLE
third_issue_bounty

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#82]
third_issue_bounty

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x842b7aa6eac7a1ae5850df53b7f399d268e31815045ca583146b7137da8ffe94](https://ropsten.etherscan.io/tx/0x842b7aa6eac7a1ae5850df53b7f399d268e31815045ca583146b7137da8ffe94)
