### ISSUE TITLE
issue_to_check_a_lot_of_claims

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#85]
issue_to_check_a_lot_of_claims

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe1ab30ffbcbb912ef38d7dc7688f221324c4447f9087a34761239e511b905f90](https://ropsten.etherscan.io/tx/0xe1ab30ffbcbb912ef38d7dc7688f221324c4447f9087a34761239e511b905f90)
