### ISSUE TITLE
Issue-a-lot-of-claims

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#86]
Issue-a-lot-of-claims

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x0ca8ec7790f220d4b341447acd4060adb2e68be654a3ac33bd7d986af5f1b8fd](https://ropsten.etherscan.io/tx/0x0ca8ec7790f220d4b341447acd4060adb2e68be654a3ac33bd7d986af5f1b8fd)
