### ISSUE TITLE
Issue_to_check one claim

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#90]
Issue_to_check one claim

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0xbfc93f2038baff25d4c84a603e52c4e896f895a9332a5e69dd26f894827c83bb](https://ropsten.etherscan.io/tx/0xbfc93f2038baff25d4c84a603e52c4e896f895a9332a5e69dd26f894827c83bb)
