### ISSUE TITLE
Deploy-contract-get-merged-PR

### ISSUE THREAD

**Issue by Chu127001** [TestingEnvENV/TestEnvAtt5#92]
Deploy-contract-get-merged-PR

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x4c6d68176d13a61030a022bdaaaeb8c47b1e8b174932ec302479d984e752bdf5](https://ropsten.etherscan.io/tx/0x4c6d68176d13a61030a022bdaaaeb8c47b1e8b174932ec302479d984e752bdf5)
